# Generated by Django 4.1.7 on 2024-02-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0044_alter_lead_additional_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
