# Generated by Django 4.1.7 on 2024-03-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
