# Generated by Django 4.1.7 on 2024-03-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0050_remove_lead_running_promotions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
