# Generated by Django 4.1.7 on 2024-03-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0052_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
