# Generated by Django 4.1.7 on 2024-03-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0058_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
