# Generated by Django 4.1.7 on 2024-03-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0060_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
