# Generated by Django 4.1.7 on 2024-04-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0062_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
